name: Calendar Agent

on:
  schedule:
    - cron: "30 2 * * *"  # runs every dat at 8am (IST)
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Restore token.json and credentials.json
        run: |
          echo "${{ secrets.TOKEN_JSON }}" | base64 -d > token.json
          echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > credentials.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
